// src/auth/constants/config.constants.ts
export const AUTH_CONFIG = {
    JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
    JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
    JWT_ACCESS_EXPIRATION: 'JWT_ACCESS_EXPIRATION',
    JWT_REFRESH_EXPIRATION: 'JWT_REFRESH_EXPIRATION',
    SESSION_SECRET: 'SESSION_SECRET',
    SESSION_MAX_AGE: 'SESSION_MAX_AGE',
    SESSION_PREFIX: 'SESSION_PREFIX',
    SESSION_LOGGING: 'SESSION_LOGGING',
    SESSION_METRICS: 'SESSION_METRICS',
    SESSION_REPORT_INTERVAL: 'SESSION_REPORT_INTERVAL',
  };
  
  export const PROVIDER_CONFIG = {
    GOOGLE: {
      CLIENT_ID: 'GOOGLE_CLIENT_ID',
      CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
      CALLBACK_URL: 'GOOGLE_CALLBACK_URL',
    },
    DISCORD: {
      CLIENT_ID: 'DISCORD_CLIENT_ID',
      CLIENT_SECRET: 'DISCORD_CLIENT_SECRET',
      CALLBACK_URL: 'DISCORD_CALLBACK_URL',
    },
    GITHUB: {
      CLIENT_ID: 'GITHUB_CLIENT_ID',
      CLIENT_SECRET: 'GITHUB_CLIENT_SECRET',
      CALLBACK_URL: 'GITHUB_CALLBACK_URL',
    },
    X: {
      CLIENT_ID: 'X_CLIENT_ID',
      CLIENT_SECRET: 'X_CLIENT_SECRET',
      CALLBACK_URL: 'X_CALLBACK_URL',
    },
  };